apiVersion: apps/v1
kind: Deployment
metadata:
  name: satya-deployment1
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: satya-deployment1
    spec:
      containers:
      - name: satya-container
        image: prakashsatya22/project3:latest
        ports:
        - containerPort: 80
