apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: satya-deployment1
    kubectl patch svc my-service -p '{"spec":{"selector":{"app":"satya-deployment1"}}}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
